/*
 *  Copyright (C) 2013, Thomas Obenaus. All rights reserved.
 *  Licensed under the New BSD License (3-clause lic)
 *  See attached license-file.
 *
 *	Author: 	Thomas Obenaus
 *	EMail:		obenaus.thomas@gmail.com
 *  Project:    JavaComponents/Widgets
 */
package thobe.widgets.splitPanel;

/**
 * Interface that can be used to listen for events generated by the {@link SPSubFrame} (split,
 * maximize, minimize, close, content switch).
 * @author Thomas Obenaus
 * @source SPTreeLeafListener.java
 * @date 13.02.2012
 */
public interface SPSubFrameListener
{
	/**
	 * Called whenever the subframe should be splitted vertically
	 * @param leaf - the leaf to be splitted
	 */
	public void onVerticalSplit( SPSubFrame leaf );

	/**
	 * Called whenever the subframe should be splitted horizontally
	 * @param leaf - the leaf to be splitted
	 */
	public void onHorizontalSplit( SPSubFrame leaf );

	/**
	 * Called whenever the subframe should be maximized
	 * @param leaf - the leaf to be maximized
	 */
	public void onMaximize( SPSubFrame leaf );

	/**
	 * Called whenever the subframe should be minimized
	 * @param leaf - the leaf to be minimized
	 */
	public void onMinimize( SPSubFrame leaf );

	/**
	 * Called whenever the subframe should be closed
	 * @param leaf - the leaf to be closed
	 */
	public void onClose( SPSubFrame leaf );

	/**
	 * Called whenever the content of the {@link SPSubFrame} was switched to another one
	 * @param leaf - the leaf whose content was switched
	 * @param key - the key representing the new content
	 */
	public void onContentSwitched( SPSubFrame leaf, String key );
}
